### ISSUE TITLE
AltaAfiliado: Numeración de Familiares

### ISSUE THREAD

**Issue by SantiBalbiani** [SantiBalbiani/TP_GDD_2C_2016#10]
Se requiere que se puedan dar de alta Afiliados junto con sus familiares.
El nro de afiliado a insertarse debe terminar con 001 para el padre, 002 para la esposa y de 003 en adelante para los hijos.

**Comment by SantiBalbiani** [comment]
Loren, subí un Fix y desde el front anda todo al 100% OK.
Se pueden insertar esposa y cualquier cant de hijos.
Falta que modifiques el SP para que haga la concatenación.
Para la concatenación te sugiero que pases todo a varchar con Convert, lo concatenes y dps lo pases a numero.
Esto lo digo porque la concatenación numérica no sirve cuando las unidades(décima, centésima, etc) pueden cambiar.

Abzo

**Comment by gutilorenzo** [comment]
Cerrado este Issue
