### ISSUE TITLE
ABM HomeAdmin - No trae el nombre de admin

### ISSUE THREAD

**Issue by ctabarez** [SantiBalbiani/TP_GDD_2C_2016#11]
Entro a Menu Principal -> Falta cargar nombre de usuario - Arriba a la derecha deberia decir el nombre del admin o admin. .

**Comment by ctabarez** [comment]
No hay tabla de administradores --> Que hacemos respecto a esto?
Ya hardcoree que diga admin y deje le codigo a medio hacer en caso de crear la tabla.

**Comment by SantiBalbiani** [comment]
Pone este issue en stand by.
Hay que resolver el milestone(Grupo de issues) 
https://github.com/SantiBalbiani/TP_GDD_2C_2016/milestone/1

**Comment by SantiBalbiani** [comment]
@ctabarez , en el grupo se decidió que el admin es un usuario genérico y en el enunciado no pide que tenga nombre, apellido, etc explícitamente.
Así que solo hay que borrar el campo nombre del form Admin y listo... de ultima hardcodear bienvenido "Administrador" y listo

**Comment by ctabarez** [comment]
Se saca campo y se agrega mensaje de bienvenida.
