### ISSUE TITLE
Hacer TEST de Todo lo referente a ROLES

### ISSUE THREAD

**Issue by ctabarez** [SantiBalbiani/TP_GDD_2C_2016#14]
Menu ROl - Sin revisar - VER 

Desde HOme Admin entrar al MEnu de roles, y revisar TODO. Cosa por cosa para ver:
Donde rompe. 
Donde no hace nada. 
Donde no hace lo que deberia hacer.
Donde anda bien.

**Comment by SantiBalbiani** [comment]
@larammolina , los bugs que encuentres como resultado de este testing levantalos como issues individuales.

**Comment by larammolina** [comment]
joya. ahi los subi.

**Comment by larammolina** [comment]
Habilitar Rol, anda, falta validacion.
Modificar Rol anda. Hubo cambios en forms. 
Eliminar Rol anda.
Crear Rol con funcionalidades anda.
