### ISSUE TITLE
Form Registrar Llegada

### ISSUE THREAD

**Issue by ctabarez** [SantiBalbiani/TP_GDD_2C_2016#15]
Logeado como admin..
En buscar por especialidad, deberia quedar una opcion "no sabe"; porque una vez que se abre ese comboBox, si no sabemos cual es, no podemos dejar "ninguna alternativa", si o si hay que poner una.
(Respecto a eso se puede borrar el texto con suprimir..... pero es algo desprolijo) Seria una mejora

Ademas.....Este form, pincha al tocar "boton buscar" bajo ciertas condiciones. Realizar pruebas cambiando los filtros dos o 3 veces y tocar buscar. queda inestable.

**Comment by SantiBalbiani** [comment]
La primera parte de este issue es una mejora que no está pedida en el TP. Se tiene que acordar por lo menos el nombre, el apellido o la especialidad que pidió. Sino que se trate de alzheimer el afiliado.
La segunda parte fué corregida en el issue #46 

Se cierra Issue
