### ISSUE TITLE
Mejoras y terminar testeo completo - Alta afiliado - alta familiar - conyuge - hijos

### ISSUE THREAD

**Issue by ctabarez** [SantiBalbiani/TP_GDD_2C_2016#16]
Alta nuevo afiliado, al entrar permite cargar pareja, (boton activado); si bien despues al elegir soltero se desactiva, deberia venir desactivado facil de cambiar...
Aca el cancelar no vuelve al mismo form sino que instancia nuevo menu.... se nota por la visual en cascada de cada uno que abre. Mejorar eso.
No se verifica si impacta en BD la carga de afiliado/pareja/hijos

**Comment by SantiBalbiani** [comment]
Entiendo que aca hay 3 cosas para hacer:

Al entrar permite cargar pareja, (boton activado); si bien despues al elegir soltero se desactiva, deberia venir desactivado facil de cambiar.  Esto no lo entiendo muy bien, como debería funcionar?? @ctabarez 

Aca el cancelar no vuelve al mismo form sino que instancia nuevo menu.... se nota por la visual en cascada de cada uno que abre. Mejorar eso. OK, esto si lo entendí.

No se verifica si impacta en BD la carga de afiliado/pareja/hijos. A que te referís @ctabarez ? Actualmente cuando terminas de cargar un MessageBox te dice que se insertaron los datos.

@gutilorenzo , dudas?

**Comment by gutilorenzo** [comment]
Quedo listo y funcionando con ultimo Commit
