### ISSUE TITLE
Form Alta Familiar - Mejora y Bug - Pincha

### ISSUE THREAD

**Issue by ctabarez** [SantiBalbiani/TP_GDD_2C_2016#17]
Alta familiar-> 
Despues de entrar si se presiona volver atras sin hacer nada, tira que faltan completar campos !!! ¡?¡?? Y pincha y se cierra todo.

**Comment by gutilorenzo** [comment]
Este form se decidio sacarlo. Ya que verificamos por enunciado que solo vamos a dar alta todos de una sola vez.
