### ISSUE TITLE
Asignar Rol a Usuario

### ISSUE THREAD

**Issue by larammolina** [SantiBalbiani/TP_GDD_2C_2016#22]
Falta test y revisar SP.
Yo me encargo de este tema.

**Comment by larammolina** [comment]
@SantiBalbiani como me asigno este issue ?

**Comment by larammolina** [comment]
PINCHA: NO TOMA LOS SP

asignarRol

CREATE PROCEDURE [SELECT_GROUP].[asignarRol](@ROL VARCHAR(45), @username VARCHAR(45))
AS
BEGIN

if exists ((SELECT * FROM SELECT_GROUP.Usuario_Por_Rol where usuario_username=@rol and rol_idRol=@rol

begin 
print('Ya existe la asignacion para el Usuario:'+@username'con el Rol:'+@rol)
return
end

begin
INSERT INTO SELECT_GROUP.Usuario_Por_Rol(@ROL,@username)
end
GO


Tampoco reconoce

desasignarRol

CREATE PROCEDURE [SELECT_GROUP].[desasignarRol](@ROL VARCHAR(45), @username VARCHAR(45))
AS
BEGIN

begin
DELETE FROM SELECT_GROUP.Usuario_Por_Rol(@username, @ROL)
WHERE rol_idROL = @ROL and usuario_username=@username

end
GO

**Comment by SantiBalbiani** [comment]
@larammolina , Te doy una mano en esto.

**Comment by larammolina** [comment]
dale, si queres hacemos hangouts.

**Comment by SantiBalbiani** [comment]
Testeo de funcionalidad OK. Cierro Issue.
