### ISSUE TITLE
Abm Afiliado: Baja de Afiliado

### ISSUE THREAD

**Issue by SantiBalbiani** [SantiBalbiani/TP_GDD_2C_2016#23]
Se deberá dar de baja el usuario del afiliado a nivel lógico.
Para eso crear un nuevo campo Habilitado en Usuario.

**Comment by SantiBalbiani** [comment]
El campo Usuario.habilitado = 1 es que está habilitado.
El campo Usuario.habilitado = 0 es que está inhabilitado.

**Comment by ctabarez** [comment]
Imagino que quisiste poner 
El campo Usuario.habilitado = 1 es que está habilitado.
El campo Usuario.habilitado = 0 es que está inhabilitado.

**Comment by SantiBalbiani** [comment]
@ctabarez  sisi, ahi lo cambié. Gracias!

**Comment by larammolina** [comment]
Cambios commiteados a la fecha 06/12/2016

**Comment by larammolina** [comment]
Falta concatenar el apellido en el form de baja afiliado el check list box

**Comment by larammolina** [comment]
foreach (DataRow idAfi in afiliados.Rows)
            {
                ComboboxItem unAfiliado = new ComboboxItem();

                string nombre = idAfi["nombre"].ToString();
                string apellido = idAfi["apellido"].ToString();


                unAfiliado.Text = nombre+"," +apellido;
                
                unAfiliado.Value = idAfi["idAfiliado"].ToString();

                checkedListBox1.Items.Add(unAfiliado);

            }

**Comment by larammolina** [comment]
namespace ClinicaFrba.Abm_Afiliado
{
    public partial class BajaAfiliado : Form
    {
        public BajaAfiliado()
        {
            InitializeComponent();
        }

        private void BajaAfiliado_Load(object sender, EventArgs e)
        {

            Conexion.conectar();
            DataTable afiliados = new DataTable();

            string consultaStr = "select idAfiliado, nombre, apellido from SELECT_GROUP.Afiliado where afiliado.habilitado=1";

            afiliados = Conexion.LeerTabla(consultaStr);

            DataTable nombreRoles = new DataTable();


            foreach (DataRow idAfi in afiliados.Rows)
            {
                ComboboxItem unAfiliado = new ComboboxItem();

                string nombre = idAfi["nombre"].ToString();
                string apellido = idAfi["apellido"].ToString();


                unAfiliado.Text = nombre+"," +apellido;
                
                unAfiliado.Value = idAfi["idAfiliado"].ToString();

                checkedListBox1.Items.Add(unAfiliado);

            }


        }

        private void btnActualizar_Click(object sender, EventArgs e)
        {

            //Conexion.conectar();
            SqlConnection conexion;
            bool conectado = false;
            //llenar la variable conexión con los parámetros de la variable parametros
            string parametros = ConfigurationManager.ConnectionStrings["miCadenaConexion"].ConnectionString;
            conexion = new SqlConnection(parametros);
            try
            {
                //abrir la conexion
                conexion.Open();
                conectado = true;
            }
            catch (InvalidCastException)
            {
                MessageBox.Show("Error al conectar la Base de datos");
                conectado = false;
            }


            if (conectado == true)
            {

                try
                {

                    if (checkedListBox1.CheckedItems.Count > 0)
                    {

                        foreach (Object item in checkedListBox1.CheckedItems)
                        {

                            ComboboxItem unItem = new ComboboxItem();

                            unItem = (ComboboxItem)item;

                            //le pone el valor 0 al afiliado eliminado 
                            SqlCommand cmdRol = new SqlCommand("update Select_group.Afiliado set habilitado=0 where nombre=@nombreAfiliado", conexion);
                            cmdRol.Parameters.AddWithValue("@nombreAfiliado", unItem.Text);
                            cmdRol.ExecuteNonQuery();
                            MessageBox.Show("Afiliado ha sigo eliminado con exito ");
                            Conexion.conexion.Close();
                        }





                    }

                    else
                    {
                        MessageBox.Show("Porfavor seleccione al menos un Afiliado");
                    }

                    while (checkedListBox1.CheckedItems.Count > 0)
                    {
                        checkedListBox1.SetItemChecked(checkedListBox1.CheckedIndices[0], false);
                    }

                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }


            }

        }

        private void button2_Click(object sender, EventArgs e)
        {
            Menu_Principal.HomeAdmin frmadmin = new Menu_Principal.HomeAdmin();
            frmadmin.Show();
            this.Close();
        }
    }
}

**Comment by SantiBalbiani** [comment]
Funcionalidad Testeada OK. Se cierra Issue.
