### ISSUE TITLE
Menu Principal: Form HomeCustom

### ISSUE THREAD

**Issue by SantiBalbiani** [SantiBalbiani/TP_GDD_2C_2016#27]
Realizar un nuevo Home para los roles custom (Es decir, los que no son estándar, léase Afiliado, Profesional y Admin).
Este Form Custom tiene que tener un botón por cada funcionalidad disponible.
Además, tiene que habilitar solo los botones que ese rol le permite.

**Comment by ctabarez** [comment]
Form Funcionando.  Falta acomodar un poco el login pero Actualmente: 
Sin importar con quien logee vas acá. (ESTO DEJEMOSLO ASI para solucionar un tema en la correcion y ser mas ordenados, usando un unico form como pensamos en su momento)...

Andan todos los botones, ida y vuelta. El menu se queda siempre abierto, a menos que se cierre la sesion para mantener la integridad de la "Sesion"

Comprar Bonos y Cambiar Plan andan bien desde este form. 

Reconoce el Rol que le pasamos de la seleccion de Roles y lo muestra. 

Carga la informacion del usuario que se logeo, ( si es Afiliado o profesional unicamente) --

**Comment by SantiBalbiani** [comment]
@ctabarez  Entiendo que de esto falta ver que ejecute bien la lógica de los botones no?

**Comment by ctabarez** [comment]
Custom OK
