### ISSUE TITLE
Asignar/Desasignar ROL

### ISSUE THREAD

**Issue by ctabarez** [SantiBalbiani/TP_GDD_2C_2016#34]
Esta mal que haya que ingresar en text los roles a asignar y desasignar. 

A asignar: Seleccionar desde un comboBOx -> las 3 opciones.
A desasignar: Que Valide contra la BD cuales tiene y carge un ComboBox para elegir cual sacar.

**Comment by ctabarez** [comment]
Sacando eso, Intente asignarle un Rol "Afiliado" me tiro que no existe
No se encontró el procedimiento almacenado 'Select_Group.asignarRol'.


![imagen](https://cloud.githubusercontent.com/assets/4109757/20912799/356621a8-bb51-11e6-9955-c700529fad53.png)

Y al aceptar ese Boton, me devuelve al HOME Afiliado, y no al de admin como deberia ser..

**Comment by SantiBalbiani** [comment]
Se cierra este Issue por estar duplicado con el #22
