### ISSUE TITLE
Abm Afiliado: Alta Afiliado

### ISSUE THREAD

**Issue by ctabarez** [SantiBalbiani/TP_GDD_2C_2016#35]
Testeando esta funcionalidad veo que: 

Sí crea un usuario. 

No es un afiliado, sino un usuario, ya que se crea en la BD Afiliado, pero no tiene ROL de afiliado. 
Por lo que no puede logearse como AFILIADO... sino que queda en un LIMBO. 
Y como asignar ROL NO ANDA, no le podemos dar ROL: 

Directamente al crear nuevo afiliado. Debemos asignarle el ROL Afiliado, para que se pueda logear al sistema.

**Comment by SantiBalbiani** [comment]
Claro, no anda porque el sp tiene la mitad del código comentado... y si lo dechcomentamoch?

**Comment by gutilorenzo** [comment]
Se hizo sp y metodo dentro de EstructuraBD para resolver este BUG

**Comment by SantiBalbiani** [comment]
Hay un error al momento de dar de alta el afiliado.

**Comment by SantiBalbiani** [comment]
Pincha en el alta de Afiliado porque no reconoce la columna "nombre" del dataRow.
Verificar orden de columnas y que se le esté pasando a la función el parámetro correcto por Debug.

**Comment by gutilorenzo** [comment]
Quedo funcionando con el ultimo Commit.
