### ISSUE TITLE
Form Registrar Agenda Medico

### ISSUE THREAD

**Issue by larammolina** [SantiBalbiani/TP_GDD_2C_2016#39]
#Registrar Agenda Profesional
- Para esta funcionalidad tienen que desarrollar una pantalla desde la cual se pueda dar de alta una nueva agenda.  Fijense lo que indica el enunciado.

**Comment by larammolina** [comment]
Testeando.

**Comment by SantiBalbiani** [comment]
@larammolina  no te olvides de validar que un profesional no meta mas de una registro para el mismo día.

**Comment by larammolina** [comment]
@SantiBalbiani estoy en eso!

**Comment by larammolina** [comment]
testeado OK!
