### ISSUE TITLE
ABM ROL: Lógica de Visualizacion de Botones

### ISSUE THREAD

**Issue by SantiBalbiani** [SantiBalbiani/TP_GDD_2C_2016#43]
- Se modificó el rol afiliado agregando la funcionalidad de Listado estadistico y al acceder a la pantalla no se visualiza la misma.Las funcionalidades pueden variar, por lo tanto no deben ser fijas.

- Al querer asignarle un rol a un usuario se obtuvo el msg que no se encontró el procedimiento select_group.asigna_rol.
El mismo no se encuentra en el script de migración.

**Comment by larammolina** [comment]
Falta la logica de que te muestre los botones correspondientes en relacion a las funcionalidades que posee el rol.

Sobre el tema de asignar rol, ya anda todo.

**Comment by SantiBalbiani** [comment]
@larammolina , @ctabarez 
Acabo de generar la lógica que en base al rol elegido carga una lista global de strings con los nombres de las funcionalidades, en base a las mismas, tienen que validar que botones se prenden y cuales no.

**Comment by ctabarez** [comment]
Se cargan botones desde cualquier form. 

Si se cierra sesion y se inicia con otro , se cargan MAL. 

Es necesario Detener la Ejecucion del programa y volver a correr para que se cargue bien..
Algo debe quedar cargado en cache o en algun lado..

**Comment by ctabarez** [comment]
Se  modifica cerrar sesion para que funcione correctamente en todos los casos
