### ISSUE TITLE
ABM Afiliado

### ISSUE THREAD

**Issue by SantiBalbiani** [SantiBalbiani/TP_GDD_2C_2016#45]
- No validan que el Dni no este duplicado. Revisen que en el caso de error, queda con incosistencia ya que quedan grabados los datos a nivel usuario.
- Se intentó modificar los datos de un afiliado pero al presionar el botón no realiza acción alguna.
- Se intentó dar de baja un afiliado pero al presionar el botón no realiza acción alguna.
- En la pantalla de cambio de plan, en plan actual se visualiza el id en vez de la descripción.
- Se dió de alta un familiar, se seleccionó la opción conyugue, se cargaron los datos y se obtuvo un error.

**Comment by gutilorenzo** [comment]
Lo de validar DNI ya esta. El resto en que estado esta?

**Comment by SantiBalbiani** [comment]
@gutilorenzo 
La modificacion está OK.
La baja anda pero tira select *
Si te parece levanto un issue solo para esto último

**Comment by gutilorenzo** [comment]
Dale. Yo me encargo si queres de la baja para mejorarla

**Comment by SantiBalbiani** [comment]
@gutilorenzo  Listo, te generé el issue #54 

Cierro este issue.
