### ISSUE TITLE
Compra de Bonos: Boton "Ir atrás"

### ISSUE THREAD

**Issue by SantiBalbiani** [SantiBalbiani/TP_GDD_2C_2016#5]
**Compra de Bonos:**
Cuando se clickea en "ir atras" estando logueado como Afiliado, te lleva al Home Afiliado.
Pero cuando se clickea en "ir atras" estando logueado como Administrativo, te lleva al Home Afiliado, en vez de al Home Admin.

**Comment by ctabarez** [comment]
Resuelto
