### ISSUE TITLE
Cambio de Plan

### ISSUE THREAD

**Issue by SantiBalbiani** [SantiBalbiani/TP_GDD_2C_2016#50]
Tiene que aparecer la Descripción en lugar del Id Plan.

**Comment by SantiBalbiani** [comment]
@larammolina :Se adjunta Foto donde se indica que esta apareciendo el idPlan en vez de la descripcion del plan

![cambioplan](https://cloud.githubusercontent.com/assets/8622255/21077383/5ab0703c-bf28-11e6-80c6-149dccedab29.jpg)

**Comment by larammolina** [comment]
Testeado. OK.
Se agrego una linea con la descripcion.
