### ISSUE TITLE
Registrar Diagnostico desde HomeCustom

### ISSUE THREAD

**Issue by ctabarez** [SantiBalbiani/TP_GDD_2C_2016#58]
Agregar Logica al boton.... la dejo comentada

Tambien desde HomeAdmin, mismo boton. Registrar Diagnostico

Tambien desde HomeAfiliado...

**Comment by ctabarez** [comment]
Listo, Verificamos en grupo de Gestiion, 

Y definimos que esta fuera del alcance de la funcionalidad

**Comment by SantiBalbiani** [comment]
@ctabarez , porfa poné aca el link o un print screen del mail. Así tenemos de respaldo. Gracias.
