### ISSUE TITLE
Error: Test Cambio de plan para el afiliado 101 desde Admin

### ISSUE THREAD

**Issue by larammolina** [SantiBalbiani/TP_GDD_2C_2016#59]
![cambiar_plan](https://cloud.githubusercontent.com/assets/8785267/21086901/93679770-bfff-11e6-8d80-fd6d3dcdfe13.PNG)

**Comment by SantiBalbiani** [comment]
El error es bastante claro, le estan pasando un string cuando quiere un int.
En este caso le pasan al campo idPlan una descripción
![fijensebieeen](https://cloud.githubusercontent.com/assets/8622255/21087288/578cdd60-c003-11e6-8898-44c91f12aa60.png)
