### ISSUE TITLE
Error Test: desde Profesional, al apretar el boton Registrar Diagnostico.

### ISSUE THREAD

**Issue by larammolina** [SantiBalbiani/TP_GDD_2C_2016#63]
Excepción no controlada del tipo 'System.Data.SqlClient.SqlException' en System.Data.dll

Información adicional: La conversión del tipo de datos varchar en datetime produjo un valor fuera de intervalo.

**Comment by SantiBalbiani** [comment]
Se cierra porque no es un error de la aplicación.
