### ISSUE TITLE
Error Test: al ingresar con el Rol Afiliado desde Admin, previamente asignado.

### ISSUE THREAD

**Issue by larammolina** [SantiBalbiani/TP_GDD_2C_2016#64]
![rol_afiliado](https://cloud.githubusercontent.com/assets/8785267/21087859/6472e52e-c008-11e6-9b1b-f1005d115bd7.PNG)

**Comment by SantiBalbiani** [comment]
Hay un problema con el cierre de sesión.
Al usar el método restart() no limpia variables.
