### ISSUE TITLE
Proceso de un Afiliado [Camino Verde]

### ISSUE THREAD

**Issue by SantiBalbiani** [SantiBalbiani/TP_GDD_2C_2016#66]
1. Comprar un Bono.
2. Solicitar un Turno.
3. Recepcionar Afiliado. (Despues editar fecha y hora)
4. Registrar Diagnostico.

Chequear mensajes y datos grabados en tablas sean consistentes

**Comment by larammolina** [comment]
Se creo una vm nueva con un windows 7 y se bajaron todos los archivos de la catedra desde la pagina de gdd utn, no avanza el inicio de sesion, el admin figura sin roles.

**Comment by SantiBalbiani** [comment]
@larammolina, se crearon los registros de roles para el usuario admin en la tabla correspondiente? Tuviste algun error en el script de creación? En caso afirmativo pasa capturas de pantalla.

**Comment by larammolina** [comment]
1. Compra bono OK
2. Solicitar Turno OK

**Comment by larammolina** [comment]
3. Recepcionar llegada OK

**Comment by larammolina** [comment]
![recepcion_llegada](https://cloud.githubusercontent.com/assets/8785267/22628104/ec21c380-ebac-11e6-80b2-cb5c2afaf04e.PNG)

**Comment by larammolina** [comment]
4. Cambio de fecha
![cambio_fecha](https://cloud.githubusercontent.com/assets/8785267/22628159/ea39bf40-ebad-11e6-96d7-cbe26cc57458.PNG)

5.Registrar diagnostico desde medico ERROR

![error_registrar](https://cloud.githubusercontent.com/assets/8785267/22628164/fabc3b7c-ebad-11e6-8f6f-1559680a76f3.PNG)

**Comment by larammolina** [comment]
5 Registrar diagnostico oK 
![registrar_diagnostico](https://cloud.githubusercontent.com/assets/8785267/22628556/cae6e062-ebb4-11e6-8342-8a76d88fa9cd.PNG)

**Comment by larammolina** [comment]
Consultas en la base OK.
