### ISSUE TITLE
Proceso de un Afiliado [Cancela Afiliado]

### ISSUE THREAD

**Issue by SantiBalbiani** [SantiBalbiani/TP_GDD_2C_2016#67]
Comprar un Bono.
Solicitar un Turno.
Afiliado Cancela Turno

Chequear mensajes y datos grabados en tablas sean consistentes

**Comment by larammolina** [comment]
compra Bono OK.
solicita turno OK.

**Comment by larammolina** [comment]
Cancelar turno no muestra los turnos del Afiliado, y en caso de no tenerlos, no informa que el Afiliado no posee turnos a cancelar.

**Comment by larammolina** [comment]
Cancelar turno OK.
PERO, cuando se confirma la cancelacion, se cierran las ventanas del sistema.

**Comment by larammolina** [comment]
Cancela turno OK.
