### ISSUE TITLE
Proceso de un Afiliado [Cancela Profesional]

### ISSUE THREAD

**Issue by SantiBalbiani** [SantiBalbiani/TP_GDD_2C_2016#68]
1. Comprar un Bono.
2. Solicitar un Turno.
3. Profesional: Cancelar dias (Seleccionar un rango de 3 días)
4. Intentar Recepcionar Afiliado. (No debería poder)

Chequear mensajes y datos grabados en tablas sean consistentes

**Comment by gutilorenzo** [comment]
Se procede a realizar el test.

**Comment by gutilorenzo** [comment]
Agarramos usuario Afiliado numeroDoc = 72215288, idAfiliado = 1. 
Realizamos la compra de 1 bono, se realiza sin problemas y se verifica que impacta en la BD con idCompra =16649 y idBono = 145601

**Comment by gutilorenzo** [comment]
Se puede seleccionar un turno fuera del horario de la clinica, porque solo controla que el lunes este dentro del horario de la clinica.
Solicitar turno rompe al confirmar el turno.
Cancelar turno rompe avisa que sp_cancelacionProfesional tiene demasiados argumentos.

**Comment by gutilorenzo** [comment]
Arreglado ya el tema de Agenda procedemos a continuar secuencia. Nos Logeamos con Afiliado NumeroDoc = 72215288, compramos un bono nuevamente con IdCompra = 16650 y idBono = 145602. Se verifica que el campo bonoConsulta_FechaImpresion se guarda con fecha 2016-12-16 11:04:00.000 @SantiBalbiani  es correcto como se guarda este ultimo campo?

**Comment by gutilorenzo** [comment]
Al confirmar un turno seleccionado, con un profesional (anteriormente cargado sus horarios correctamente)  rompe el programa con una excepcion "La conversión del tipo de datos varchar en datetime produjo un valor fuera de intervalo." Verificarlo

**Comment by larammolina** [comment]
![turnos_cancelados_por_profesional](https://cloud.githubusercontent.com/assets/8785267/22632572/6053c4dc-ebf9-11e6-871d-ccdcab859008.PNG)

**Comment by larammolina** [comment]
en la bd, se ven los turnos en estado 2, cancelados. se cancelaron los turnos del lunes 6 y jueves 9 de febrero de 2017

**Comment by larammolina** [comment]
![turnos_cancelados](https://cloud.githubusercontent.com/assets/8785267/22632607/b2ace10a-ebf9-11e6-9906-632bbbd906f1.PNG)

**Comment by SantiBalbiani** [comment]
@gutilorenzo, si, es correcto porque la fecha del sistema esta seteada en 16-12-2016.
Si queres podes cambiarla desde properties -> settings
