### ISSUE TITLE
Proceso de un Afiliado [Se Retira Antes] 

### ISSUE THREAD

**Issue by SantiBalbiani** [SantiBalbiani/TP_GDD_2C_2016#69]
1. Comprar un Bono.
2. Solicitar un Turno.
3. Recepcionar Afiliado. (Despues editar fecha y hora)
4. Registrar Diagnostico. (Indicar que no se completó el diagnostico)

Chequear mensajes y datos grabados en tablas sean consistentes

**Comment by larammolina** [comment]
Comprar un bono. Ok
Solicitar turno OK.

**Comment by SantiBalbiani** [comment]
@larammolina  para el punto .4 por favor subí la captura con el mensaje de OK y una captura de los datos de la base finalzados

**Comment by larammolina** [comment]
registrar diagnostico ok.
![diagnostico_se_fue_antes](https://cloud.githubusercontent.com/assets/8785267/22631564/5b0e3cba-ebee-11e6-81e0-f2bc3318edd9.PNG)

**Comment by larammolina** [comment]
![turno_ cancelado](https://cloud.githubusercontent.com/assets/8785267/22631886/fdfcb4ac-ebf2-11e6-931c-f39f757ff219.PNG)

**Comment by larammolina** [comment]
Estado 2 cancelado.
