### ISSUE TITLE
ABM: Habilitar Rol Eliminado

### ISSUE THREAD

**Issue by SantiBalbiani** [SantiBalbiani/TP_GDD_2C_2016#7]
Maca:

- Agregar validación para que cuando no hay roles eliminados y se hace click en Habilitar Rol, que un mensaje indique "no existen Roles Eliminados".

- Agregar Título "Habilitar Rol Eliminado" a la ventana en cuestión.

**Comment by larammolina** [comment]
En proceso

**Comment by larammolina** [comment]
Listo el titulo.

**Comment by larammolina** [comment]
private void checkedListBox2_SelectedIndexChanged(object sender, EventArgs e)
        {

            if (checkedListBox2.Items.Count < 1)
            {
                MessageBox.Show("No existen roles a eliminar");
            }
        }
Todavia no muestra el mensaje

**Comment by SantiBalbiani** [comment]
Maca, no te muestra el mensaje porque lo estas poniendo en el evento "SelectedIndexChanged".
Ese código está bien, pero va en el evento LOAD del form.

**Comment by larammolina** [comment]
Ok.

**Comment by larammolina** [comment]
Falta cambiar de lugar la validacion y testear.

**Comment by larammolina** [comment]
ANDA 👯
