### ISSUE TITLE
Estrategia y DER

### ISSUE THREAD

**Issue by SantiBalbiani** [SantiBalbiani/TP_GDD_2C_2016#78]
Luego del Testing Integral.

Revisar:

- Estrategia.
- DER.

Vamos que aprobamos!! 🤓  😄

**Comment by SantiBalbiani** [comment]
Estrategia:
- Falta agregar a la estrategia las funcionalidades que creamos con su correspondiente ID, que significan los diferentes estados de los bonos, los turnos y los turnos agendados.
- Falta agregar para los roles estandar, que funcionalidades les son asignadas inicialmente.
- Falta agregar a la estrategia las decisiones que tomamos para los usuarios y contraseñas de los diferentes actores.
- Mencionar los Triggers y los DataTypes usados

**Comment by SantiBalbiani** [comment]
DER:

- Agregar el campo Agenda.Especialidad.
- Corregir la FK de Agenda.Especialidad: Debe ir a la tabla Especialidad en vez de Profesional por especialidad.
- Discutir como aclarar que en el DER tenemos tablas intermedias que en SQL no son implementadas puesto que no las necesitamos y SQL permite la relación muchos a muchos. (Ej. Compras_Por_Afiliado)

**Comment by SantiBalbiani** [comment]
Una opción para el problema del DER es editar el formato de imagen del der y ponerle muchos a muchos.

**Comment by larammolina** [comment]
1. Ok.
2. Ok.

**Comment by larammolina** [comment]
3. Ok, se borraron dos tablas.

**Comment by SantiBalbiani** [comment]
Se tienen el DER y la estrategia completos. se cierra issue
