### ISSUE TITLE
Proceso de un Admin [Funcionalidad completa]

### ISSUE THREAD

**Issue by SantiBalbiani** [SantiBalbiani/TP_GDD_2C_2016#79]
Se requiere testear:

1. - Cambio de Planes: Verificar que lo cambie y que registre el plan viejo en el historial.
2. - Compra de Bonos: Verificar que impacte en tabla Bono y Compra.
3. - Alta de Usuario: Probar con hijo con hijo y conyuge y solo.
4. - Modificacion de Usuario: Verificar que impacten ok las modificaciones.
5. - Baja de Usuario: Verificar que haga la baja.
6. - ABM Rol: Probar todas las funcionalidades de este ABM extendido.
7. - Estadisticas: Verificar que den las estadisticas.

**Comment by SantiBalbiani** [comment]
NOTA: El punto 3. se delega en el Issue #88

**Comment by SantiBalbiani** [comment]
Punto 4. Modificación de Afiliado: Anduvo OK. Subí una validación para que en nro Afiliado solamente se pueda ingresar números.

**Comment by SantiBalbiani** [comment]
Punto 5. Baja de Afiliado: Anduvo OK. Subí una validación para que en nro Afiliado solamente se pueda ingresar números.

**Comment by larammolina** [comment]
1. ok. Se cambio de plan y se registro todo en la tabla plan_ historico. plan nuevo y plan viejo.

**Comment by larammolina** [comment]
2. ok. se verifico en las tablas bono y compras, e impacta ok.

**Comment by larammolina** [comment]
6. abm rol anda bien EXCEPTO eliminar un rol. Si bien el rol es eliminado, si un usuario ya lo tenia asignado, aunque este eliminado, lo puede seguir usando. SE DEBE VALIDAR QUE AL DAR DE BAJA UN ROL, TAMBIEN SE DÈ DE BAJA LA ASIGNACION QUE TENIA CON TODOS LOS USUARIOS QUE TENIA ASIGNADOS.

**Comment by larammolina** [comment]
7. Estadisticas genera error en los 5 profesionales mas consultados.
los 5 afiliados mas consultados OK

**Comment by larammolina** [comment]
7. los 5 afiliados con mayor cantidad de bonos comprados OK

**Comment by larammolina** [comment]
error estadisticas 
![error_estadisticas](https://cloud.githubusercontent.com/assets/8785267/22671048/02a42c84-ecab-11e6-8476-49a8fee98024.PNG)

**Comment by larammolina** [comment]
6. Solucionado el problema de abm rol

**Comment by larammolina** [comment]
7. Todo estadisticas anda.

**Comment by SantiBalbiani** [comment]
Punto 3. anda OK

**Comment by SantiBalbiani** [comment]
Testeado por:
@larammolina 
@gutilorenzo 
@SantiBalbiani

Se cierra Issue.
