### ISSUE TITLE
Admin: Alta de Afiliado

### ISSUE THREAD

**Issue by larammolina** [SantiBalbiani/TP_GDD_2C_2016#88]
Probar:
1) Soltero con alta de hijo 
2)Casado con alta de hijo y alta de conyuge 
3) Soltero sin hijos

**Comment by SantiBalbiani** [comment]
Se rediseñó el front y se realizaron aclaraciones. Hay que aclarar en la estrategia que la cantidad de hijos de la pareja es informativa y en caso que se requieran ingresar hijos de la pareja se deberá hacer desde el botón agregar hijos del afiliado principal.

Diseño Anterior:
![antes](https://cloud.githubusercontent.com/assets/8622255/22660448/59f4a7fa-ec80-11e6-8585-fbe66be06c9e.png)

Diseño Nuevo:

![despues](https://cloud.githubusercontent.com/assets/8622255/22660452/5df523e8-ec80-11e6-87e8-5feedae07324.png)

**Comment by larammolina** [comment]
alta afiliado ok.

**Comment by SantiBalbiani** [comment]
#79  El punto 3. esta OK.
